### ISSUE TITLE
Could you release up to date windows binary @  triole / supervisord repo?

### ISSUE THREAD

**Issue by egg1234** [triole/web-debug-server#1]
@triole Could you release up to date windows binary @  triole / supervisord repo ?

I am borrowing this issues tab because your  triole / supervisord repo does not have Issues tab.

Thank you!

**Comment by triole** [comment]
Hi,

as far as I can see the supervisord binary is up to date. The last commit was four days ago. I built the binary release shortly after that. I might miss something. But if not feel free to close this issue.

https://github.com/triole/supervisord/releases

Cheers.

**Comment by egg1234** [comment]
@triole Thank you for your reply!

What I mean is would you release supervisord.exe for windows?

Because the original repo https://github.com/ochinchina/supervisord/releases had supervisord.exe on 03 May 2021 but no further supervisord.exe release update.

Thank you & best regards!

**Comment by triole** [comment]
Thanks for the clarification. Now I understood what you meant. Windows really isn't on my sheet that's why I must have overread your request. Anyway I added windows builds to the list. I hope it helps.

https://github.com/triole/supervisord/releases

Cheers.

**Comment by egg1234** [comment]
Thank you for your great help!

And could you release linux_armv5 version?

Because I have a merlin router want to run supervisord but the router's cpu only support armv5 instruction.

Thank you again!

**Comment by triole** [comment]
Hi,

I added arm5 to the list. Unfortunately I can not test this build myself because I don't have an arm5 device at hand. I hope it works for you.

Regards.

https://github.com/triole/supervisord/releases

**Comment by egg1234** [comment]
Thank you! 

supervisord_v22.10.24_linux_armv5l works.

But there is problem about web access in supervisord_v22.10.24_linux_armv5l and supervisord_v22.10.24_windows_x86_64.tar.gz .

My supervisord.conf like below
[inet_http_server]
port=0.0.0.0:9001

[supervisorctl]
serverurl=http://10.0.0.200:9001

The web browser report "404 page not found" when access http://10.0.0.200:9001 .

And there is no problem when I used supervisord.exe from repo https://github.com/ochinchina/supervisord/releases on 03 May 2021. It can present a web page to monitor and control supervisord.

Do you know what cause this problem?

Thank you!

**Comment by triole** [comment]
Hi,

yes I know that the web interface is broken. That's because the embedded content does not get embedded correctly. As far as I remember supervisord was even more complicated before using a handmade solution for embedding static files. Later the maintainer switched to go's native embed solution. Unfortunately it's not working as expected. I never bothered because the web interface is not important for my use cases.

But I suppose somebody would have to fix the embed stuff. An ugly workaround is to build the supervisord binary on your own machine keeping the files of the repo. If you run the binary afterwards it looks for the static files in your repo's folder and loads them from there. As soon as you remove the repository the interface is broken again. 

Sorry, I don't have a quick fix for this one.

Cheers.

**Comment by egg1234** [comment]
I see. Appreciate your comment!

Also I saw a repo https://github.com/holoto/supervisord has release a supervisord_0.7.3-SNAPSHOT-ebaef12_linux_armv5.tar.gz package.

There are two executive files in package, one is supervisord, other one is supervisord_static.
It must run supervisord and supervisord seems to call supervisord_static, the web page is normal present in this situation. But this solution is not stable, the supervisord must take many times to run, it will return shell exit code 127 when fail to run.

Thank you & best regards

**Comment by triole** [comment]
Hi again,

I think I figured it out. Turns out that sometimes it helps to look into the code. I changed my build slightly and now the static files are embedded properly. I made a new release hoping that this also solves your issue.

https://github.com/triole/supervisord/releases

Have a nice day.

Cheers.

**Comment by egg1234** [comment]
I tested armv5 and windows executive files which support web GUI perfectly. I already created an issue 
in https://github.com/ochinchina/supervisord/issues/348 informing others of your new repo release.

Appreciate your hardwork!

**Comment by triole** [comment]
Seems to be solved. I close the issue. Thanks for your cooperation and that we were able to solve this together.
